# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-27 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
